In [ ]:
!pip install tensorflow_text

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.2/5.2 MB 35.1 MB/s eta 0:00:00


In [ ]:
import pandas as pd
import numpy as np
import tensorflow as tf
import ast
from tensorflow.keras.utils import to_categorical
from sklearn.preprocessing import MultiLabelBinarizer
import tensorflow_hub as hub
import tensorflow_text as text
from tensorflow.keras.layers import Input, Dense, Lambda
from tensorflow.keras.models import Model

In [ ]:
data = pd.read_csv('github_users_dataset.csv', header=None)

initial_rows = data.shape[0]

data.dropna(inplace=True)

# Set the column names from the first row
data.columns = data.iloc[0]

# Drop the first row
data = data[1:]

# Drop all rows that are the same as the column names
data = data[~data.eq(data.columns).all(1)]

# Function to check if all strings in a given input are ASCII
def all_strings_are_ascii(input):
    if isinstance(input, list):
        return all(str(s).isascii() for s in input)
    else:
        return str(input).isascii()

# Apply the function to each element of the DataFrame
data_ascii = data.applymap(all_strings_are_ascii)

# Filter out the rows where all elements are ASCII
data = data[data_ascii.all(axis=1)]

data = data.query('projects != "[]" and languages != "[]"')

# Drop all rows where the 'role' column string has a length of less than 15
data = data[data['role'].str.len() >= 25]

# Function to check if any string in a list is less than 20 characters
def any_string_less_than_20_chars(input):
    if isinstance(input, str):
        input_list = ast.literal_eval(input)
        if isinstance(input_list, list):
            return any(len(str(s)) < 20 for s in input_list)
    return False

# Apply the function to the 'projects' column
data['any_project_less_than_20_chars'] = data['projects'].apply(any_string_less_than_20_chars)

# Drop the rows where any description in the 'projects' column is less than 20 characters
data = data[data['any_project_less_than_20_chars'] == False]

# Drop the temporary column
data.drop(columns=['any_project_less_than_20_chars'], inplace=True)

final_rows = data.shape[0]

data.to_csv('cleaned_data.csv', index=False)

print(f'Rows removed: {initial_rows - final_rows}, {100 * (initial_rows - final_rows) / initial_rows:.2f}% of the original dataset.\nYou have {final_rows} rows left.')

Rows removed: 1651, 84.71% of the original dataset.
You have 298 rows left.


In [ ]:
data.head(10)

0                                                role experience_level  \
5                 Senior Software Engineer @microsoft         Beginner   
6   Principal AI Scientist at Genentech. Formerly ...         Beginner   
8     CEO and Full-Stack Developer at SULLE WAREHOUSE         Beginner   
9   Machine learning, quantum computing, and every...         Beginner   
11                         Co-founder, @levelshealth.         Beginner   
17  Lead Engineer at Nike.\n\nMostly cloud service...     Intermediate   
21  Physical oceanographer with a love of open sou...     Intermediate   
22                        Tinker, build, make, share.     Intermediate   
26                                                :-)     Intermediate   
28             Signal processing, radar, data science     Intermediate   

0                                           languages  \
5   ['Shell', 'PowerShell', 'C#', 'Python', 'JavaS...   
6   ['Python', 'Shell', 'R', 'Jupyter Notebook', '...   
8          ['C', 'C++', 'CMake', 'Shell', 'Assembly']   
9   ['Python', 'Jupyter Notebook', 'Shell', 'C++',...   
11      ['JavaScript', 'Scala', 'CSS', 'HTML', 'PHP']   
17  ['JavaScript', 'TypeScript', 'PHP', 'CSS', 'HT...   
21  ['Jupyter Notebook', 'Python', 'HTML', 'Shell'...   
22          ['C++', 'C', 'JavaScript', 'HTML', 'CSS']   
26            ['Python', 'Shell', 'C', 'Java', 'C++']   
28  ['Shell', 'Batchfile', 'Python', 'Makefile', 'C']   

0                                       tech_keywords  \
5   ['github', 'node', 'video', 'action', 'woke', ...   
6   ['ecoli_promoter_mpra', 'training', 'women', '...   
8   ['b', 'pixels', 'linux', 'parser', 'expression...   
9   ['Cybernetics', 'elden_bot', 'quantum', 'Quant...   
11  ['sublime', 'play', 'app', 'workflow', 'exampl...   
17  ['mee.js', 'Advanced', 'class.js', 'node', 'cu...   
21  ['MLINT', 'Notebooks', 'MITgcm66h', 'publicati...   
22  ['ESP32Tests', 'eyeball_simulator', 'BlinkRC7'...   
26  ['MSRnet', 'codeBase', 'discord', 'CO224_Compu...   
28  ['setup', 'asciimatics', 'adwaita', 'icon', 'c...   

0                                            projects  
5   ['A collection of tasks to enable execution My...  
6   ['DL based processing of atac-seq data', 'Comm...  
8   ['The README for my personal GitHub account', ...  
9   ['Final Project for CSCI 2500 Computer Organiz...  
11  ['Alfred App Workflow for caniuse.com', 'Stati...  
17  ['SecretParser Plugin for the game http://www....  
21  ['Repo for the April 10-12 workshop to be held...  
22  ['Abandoned: attempt to make 15-tile sliding p...  
26  ['ABS: Scanning Neural Networks for Back-doors...  
28  ['A conda-smithy repository for adwaita-icon-t...

OHE for experience and language

In [ ]:
# unique experience levels
experience = data['experience_level'].unique()

# map unique experience levels to numbers
# categorical data --> numerical data for one-hot encoding
experience_level_mapping = {level: idx for idx, level in enumerate(experience)}

# w gpt2 nie ma potrzeby one-hot encoding
data['experience_level_num'] = data['experience_level'].map(experience_level_mapping)

# one-hot encoding !!!!!!!!!!!!
experience_level_encoded = to_categorical(data['experience_level_num'])
experience_level_encoded


array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.]], dtype=float32)

In [ ]:
data['languages'] = data['languages'].apply(ast.literal_eval)
languages = set([lang for sublist in data['languages'].tolist() for lang in sublist])

mlb = MultiLabelBinarizer(classes=sorted(languages))
languages_encoded = mlb.fit_transform(data['languages'])
languages_encoded[:1]

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

BERT for role and project

In [ ]:
bert_preprocess_url = 'https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3'
bert_model_url = 'https://tfhub.dev/tensorflow/small_bert/bert_en_uncased_L-2_H-128_A-2/2'

bert_preprocess_model = hub.KerasLayer(bert_preprocess_url)
bert_model = hub.KerasLayer(bert_model_url)

role_texts = data['role'].tolist()  # Convert 'role' column to a list

role_preprocessed = bert_preprocess_model(role_texts)

role_results = bert_model(role_preprocessed)
role_results.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'pooled_output', 'default'])

In [ ]:
roles_embedded = role_results['pooled_output']

roles_embedded.shape

TensorShape([714, 128])

In [ ]:
projects = [j for i in data['projects'].tolist() for j in ast.literal_eval(i)]

projects_preprocessed = bert_preprocess_model(projects)
projects_results = bert_model(projects_preprocessed)


In [ ]:
map_user_to_projects = {}
for user_num, projects_list in enumerate(data['projects']):
  map_user_to_projects[user_num] = ast.literal_eval(projects_list)

map_user_to_projects[0]


['A collection of tasks to enable execution MySQL commands or scripts by VSTS/TFS Windows Agents.',
 'Microsoft Azure Workshop for Developers',
 'PowerShell module for interacting with Bluetooth Low Energy (BLE) devices implementing the Generic Attribute Profile (GATT/GAP)',
 'Pre-commit hooks collection that utilizes ChatGPT and OpenAI platform to validate changes made to the codebase.',
 'This GitHub Action allows you to run Gitleaks in your GitHub workflow.',
 'A MkDocs plugin that lets you exclude/include docs files using globs, regexes, gitignore-style file and Markdown/FrontMatter tags metadata.',
 'MkDocs Video plugin',
 'OSC message decoder/encoder with fault tolerant',
 'Detect non-inclusive language in your source code.']

In [ ]:
projects_results.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'pooled_output', 'default'])

In [ ]:
projects_embedded = projects_results['pooled_output']

In [ ]:
for i in [experience_level_encoded,
          languages_encoded,
          roles_embedded,
          projects_embedded]: print(i.shape)

(714, 3)
(714, 109)
(714, 128)
(13513, 128)


In [ ]:
user_profiles = tf.concat([roles_embedded, languages_encoded], axis=1)
user_profiles.shape

TensorShape([714, 237])

In [ ]:
user_profiles[0]

<tf.Tensor: shape=(237,), dtype=float32, numpy=
array([-0.9998977 ,  0.02674753, -0.95229065,  0.07566944, -0.98473793,
        0.8515617 , -0.9891793 , -0.06120098,  0.07552765, -0.00853382,
       -0.33273837, -0.07438556, -0.13768643,  0.99698657,  0.20532432,
        0.00142703,  0.9212176 ,  0.066608  , -0.86612004, -0.28353733,
        0.5697272 ,  0.06278628, -0.8876335 , -0.82182   , -0.9968265 ,
       -0.06983151, -0.9948706 ,  0.974122  ,  0.81316996,  0.1028368 ,
        0.09937278, -0.0886519 , -0.86351496, -0.9690397 ,  0.7592347 ,
        0.996806  , -0.92572796, -0.00526048,  0.51379555, -0.9914838 ,
        0.9527194 ,  0.9840963 , -0.99205375,  0.84864724, -0.88819516,
       -0.19925441, -0.86289763,  0.9918394 , -0.5801045 ,  0.9990769 ,
       -0.5767053 , -0.9606845 , -0.01358342,  0.89274883,  0.8692733 ,
        0.59175795, -0.12701385,  0.19582532,  0.9900831 ,  0.7635511 ,
        0.08241388, -0.01632024, -0.21319991,  0.7888896 , -0.6095279 ,
       -0.998157

In [ ]:
for i in range(2):
  print(f"User {i}: {map_user_to_projects[i]}")

User 0: ['A collection of tasks to enable execution MySQL commands or scripts by VSTS/TFS Windows Agents.', 'Microsoft Azure Workshop for Developers', 'PowerShell module for interacting with Bluetooth Low Energy (BLE) devices implementing the Generic Attribute Profile (GATT/GAP)', 'Pre-commit hooks collection that utilizes ChatGPT and OpenAI platform to validate changes made to the codebase.', 'This GitHub Action allows you to run Gitleaks in your GitHub workflow.', 'A MkDocs plugin that lets you exclude/include docs files using globs, regexes, gitignore-style file and Markdown/FrontMatter tags metadata.', 'MkDocs Video plugin', 'OSC message decoder/encoder with fault tolerant', 'Detect non-inclusive language in your source code.']
User 1: ['DL based processing of atac-seq data', 'Community-curated list of software packages and data resources for single-cell, including RNA-seq, ATAC-seq, etc.', 'Hackathon team: gene expression analysis for Covid-19', 'Examples of single-cell genomic an

In [ ]:
data.head(15)

0                                                role experience_level  \
5                 Senior Software Engineer @microsoft         Beginner   
6   Principal AI Scientist at Genentech. Formerly ...         Beginner   
8     CEO and Full-Stack Developer at SULLE WAREHOUSE         Beginner   
9   Machine learning, quantum computing, and every...         Beginner   
11                         Co-founder, @levelshealth.         Beginner   
17  Lead Engineer at Nike.\n\nMostly cloud service...     Intermediate   
21  Physical oceanographer with a love of open sou...     Intermediate   
22                        Tinker, build, make, share.     Intermediate   
26                                                :-)     Intermediate   
28             Signal processing, radar, data science     Intermediate   
33  Content Writer, JavaScript Developer, and Sing...     Intermediate   
36                           iOS - Android security.          Beginner   
39  Creative, detail-oriented software engineer wi...     Intermediate   
44                   Developer, researcher, and geek.     Intermediate   
45                                 philosophy student     Intermediate   

0                                          languages  \
5        [Shell, PowerShell, C#, Python, JavaScript]   
6   [Python, Shell, R, Jupyter Notebook, Dockerfile]   
8                   [C, C++, CMake, Shell, Assembly]   
9   [Python, Jupyter Notebook, Shell, C++, Starlark]   
11               [JavaScript, Scala, CSS, HTML, PHP]   
17          [JavaScript, TypeScript, PHP, CSS, HTML]   
21      [Jupyter Notebook, Python, HTML, Shell, TeX]   
22                   [C++, C, JavaScript, HTML, CSS]   
26                     [Python, Shell, C, Java, C++]   
28           [Shell, Batchfile, Python, Makefile, C]   
33               [JavaScript, HTML, CSS, Shell, EJS]   
36         [Makefile, Shell, Python, C, Objective-C]   
39              [JavaScript, HTML, CSS, Shell, SCSS]   
44        [JavaScript, CSS, HTML, Shell, TypeScript]   
45                [Makefile, Shell, C, Python, Perl]   

0                                       tech_keywords  \
5   ['github', 'node', 'video', 'action', 'woke', ...   
6   ['ecoli_promoter_mpra', 'training', 'women', '...   
8   ['b', 'pixels', 'linux', 'parser', 'expression...   
9   ['Cybernetics', 'elden_bot', 'quantum', 'Quant...   
11  ['sublime', 'play', 'app', 'workflow', 'exampl...   
17  ['mee.js', 'Advanced', 'class.js', 'node', 'cu...   
21  ['MLINT', 'Notebooks', 'MITgcm66h', 'publicati...   
22  ['ESP32Tests', 'eyeball_simulator', 'BlinkRC7'...   
26  ['MSRnet', 'codeBase', 'discord', 'CO224_Compu...   
28  ['setup', 'asciimatics', 'adwaita', 'icon', 'c...   
33  ['client', 'game_dig', 'blog_img', 'express_to...   
36  ['Nougat', 'Jailbreak', 'osx', 'xnu', 'iOS', '...   
39  ['react', 'Algorithm', 'Reactjs', 'redux', 'da...   
44  ['react', 'mocha', '', 'date', 'notes', 'appli...   
45  ['old', 'elogind', 'discord', 'bsdunzip', 'com...   

0                                            projects  experience_level_num  
5   ['A collection of tasks to enable execution My...                     0  
6   ['DL based processing of atac-seq data', 'Comm...                     0  
8   ['The README for my personal GitHub account', ...                     0  
9   ['Final Project for CSCI 2500 Computer Organiz...                     0  
11  ['Alfred App Workflow for caniuse.com', 'Stati...                     0  
17  ['SecretParser Plugin for the game http://www....                     1  
21  ['Repo for the April 10-12 workshop to be held...                     1  
22  ['Abandoned: attempt to make 15-tile sliding p...                     1  
26  ['ABS: Scanning Neural Networks for Back-doors...                     1  
28  ['A conda-smithy repository for adwaita-icon-t...                     1  
33  ['My submission to the 2013 js13kgames.com com...                     1  
36  ['Android Full Framework for Nougat.', 'Purpos...                

In [ ]:
dataset = []

In [ ]:
len(dataset)

0

In [ ]:
len(map_user_to_projects[0])

9

In [ ]:
file = open("negative_match.txt", "r")
num_matches = len(file.read().splitlines())
file.close()
print("num matches: ", num_matches)

start_project_range = 0
for user_num, user_profile in enumerate(user_profiles):
  if user_num == num_matches: break
  for project_embedding in projects_embedded[start_project_range:start_project_range+len(map_user_to_projects[user_num])]:
    dataset.append((user_profile, project_embedding, 1))
  start_project_range += len(map_user_to_projects[user_num])



num matches:  2
len(dataset): 9
len(dataset): 19


In [ ]:
len(dataset)

19

better manual method

In [ ]:
# manual small dataset testing

def find_project_start_index_for_given_user(user_num):
  i = 0
  index = 0
  while i != user_num:
    index += len(map_user_to_projects[i])
    i += 1
  return index

def add_negative_example_given_non_matching_user_profiles_manually(user1: int, non_matching_user2: int):
  start_index = find_project_start_index_for_given_user(non_matching_user2)
  for i in range(len(map_user_to_projects[non_matching_user2])):
    dataset.append((user_profiles[user1], projects_embedded[start_index + i], 0))

def add_positive_example_given_non_matching_user_profiles_manually(user1: int, non_matching_user2: int):
  start_index = find_project_start_index_for_given_user(non_matching_user2)
  for i in range(len(map_user_to_projects[non_matching_user2])):
    dataset.append((user_profiles[user1], projects_embedded[start_index + i], 1))

In [ ]:
file = open("negative_match.txt", "r")

lines = file.read().splitlines()
neg_matches = []

for line in lines:
  first, second = line.split(",")
  neg_matches.append((int(first), int(second)))

for first, second in neg_matches:
  add_negative_example_given_non_matching_user_profiles_manually(first, second)

file.close()


In [ ]:
len(dataset)

38

In [ ]:
dataset[0]

(<tf.Tensor: shape=(237,), dtype=float32, numpy=
 array([-0.9998977 ,  0.02674753, -0.95229065,  0.07566944, -0.98473793,
         0.8515617 , -0.9891793 , -0.06120098,  0.07552765, -0.00853382,
        -0.33273837, -0.07438556, -0.13768643,  0.99698657,  0.20532432,
         0.00142703,  0.9212176 ,  0.066608  , -0.86612004, -0.28353733,
         0.5697272 ,  0.06278628, -0.8876335 , -0.82182   , -0.9968265 ,
        -0.06983151, -0.9948706 ,  0.974122  ,  0.81316996,  0.1028368 ,
         0.09937278, -0.0886519 , -0.86351496, -0.9690397 ,  0.7592347 ,
         0.996806  , -0.92572796, -0.00526048,  0.51379555, -0.9914838 ,
         0.9527194 ,  0.9840963 , -0.99205375,  0.84864724, -0.88819516,
        -0.19925441, -0.86289763,  0.9918394 , -0.5801045 ,  0.9990769 ,
        -0.5767053 , -0.9606845 , -0.01358342,  0.89274883,  0.8692733 ,
         0.59175795, -0.12701385,  0.19582532,  0.9900831 ,  0.7635511 ,
         0.08241388, -0.01632024, -0.21319991,  0.7888896 , -0.6095279 ,
  

In [ ]:
import random

# Shuffle the dataset
random.shuffle(dataset)

In [ ]:
# Split the dataset into features and labels
features = [(user_profile, project_embedding) for user_profile, project_embedding, _ in dataset]
labels = [label for _, _, label in dataset]

In [ ]:
# Convert to numpy arrays or tensors as required for training
features = np.array(features)
labels = np.array(labels)

<ipython-input-95-b8892ba2606d>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  features = np.array(features)


In [ ]:
len(labels)

38

In [ ]:
# Hyperparameters (you can adjust these based on your needs)
embedding_size = 256  # Size of the final embeddings
dropout_rate = 0.05    # Dropout rate for regularization

# User Profile Branch
user_input = Input(shape=(237,))
user_branch = Dense(128, activation='relu')(user_input)
# user_branch = tf.keras.layers.Dropout(dropout_rate)(user_branch)
user_branch = Dense(64, activation='relu')(user_branch)

# Project Description Branch
project_input = Input(shape=(128,))
project_branch = Dense(64, activation='relu')(project_input)
# project_branch = tf.keras.layers.Dropout(dropout_rate)(project_branch)
project_branch = Dense(64, activation='relu')(project_branch)

# # User Profile Branch
# user_input = Input(shape=(237,))  # Adjust the shape based on your concatenated user profile tensor
# user_branch = Dense(512, activation='relu')(user_input)

# user_branch = Dense(256, activation='relu')(user_branch)
# user_branch = tf.keras.layers.Dropout(dropout_rate)(user_branch)
# user_branch = Dense(embedding_size, activation='relu')(user_branch)

# # Project Description Branch
# project_input = Input(shape=(128,))  # Adjust the shape based on your BERT embeddings
# project_branch = Dense(256, activation='relu')(project_input)
# project_branch = tf.keras.layers.Dropout(dropout_rate)(project_branch)
# project_branch = Dense(128, activation='relu')(project_branch)
# project_branch = tf.keras.layers.Dropout(dropout_rate)(project_branch)
# project_branch = Dense(embedding_size, activation='relu')(project_branch)

In [ ]:
# Distance Layer
def euclidean_distance(vectors):
    x, y = vectors
    sum_square = tf.reduce_sum(tf.square(x - y), axis=1, keepdims=True)
    return tf.sqrt(sum_square)

# def cosine_similarity(vectors):
#     # Unpack the vectors
#     vector_a, vector_b = vectors

#     # Compute the cosine similarity
#     a_norm = tf.nn.l2_normalize(vector_a, axis=1)
#     b_norm = tf.nn.l2_normalize(vector_b, axis=1)
#     cosine_similarity = tf.reduce_sum(tf.multiply(a_norm, b_norm), axis=1)

#     # Reshape to ensure the output shape is correct
#     return tf.reshape(cosine_similarity, [-1, 1])

distance = Lambda(euclidean_distance)([user_branch, project_branch])

# Siamese Network Model
siamese_network = Model(inputs=[user_input, project_input], outputs=distance)

# Contrastive Loss Function
def contrastive_loss(y_true, y_pred):
    margin = 1
    square_pred = tf.square(y_pred)
    margin_square = tf.square(tf.maximum(margin - y_pred, 0))
    return tf.reduce_mean(y_true * square_pred + (1 - y_true) * margin_square)

# Define a custom accuracy metric
def accuracy(y_true, y_pred):
    '''Compute classification accuracy with a fixed threshold on distances.
    '''
    return tf.keras.metrics.binary_accuracy(y_true, tf.cast(y_pred < 0.5, dtype=tf.float32))

# Compile the model with the custom accuracy metric
siamese_network.compile(optimizer="adam", loss=contrastive_loss, metrics=[accuracy])

# Model Summary
siamese_network.summary()

Model: "model_5"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to                  
 input_11 (InputLayer)       [(None, 237)]                0         []                            
                                                                                                  
 input_12 (InputLayer)       [(None, 128)]                0         []                            
                                                                                                  
 dense_20 (Dense)            (None, 128)                  30464     ['input_11[0][0]']            
                                                                                                  
 dense_22 (Dense)            (None, 64)                   8256      ['input_12[0][0]']            
                                                                                            

In [ ]:
# prepare data for training

user_profiles, project_embeddings = zip(*features)
user_profiles = np.array(user_profiles)
project_embeddings = np.array(project_embeddings)
labels = np.array(labels)

In [ ]:
# Splitting data into training and validation sets
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(
    list(zip(user_profiles, project_embeddings)), labels, test_size=0.5, random_state=43
)

In [ ]:
# Preparing data for the model
user_profiles_train, project_embeddings_train = zip(*X_train)
user_profiles_val, project_embeddings_val = zip(*X_val)

In [ ]:
# Convert labels to float32
y_train = y_train.astype('float32')
y_val = y_val.astype('float32')

In [ ]:
len(user_profiles_train)

19

In [ ]:
# Training the model
history = siamese_network.fit(
    [np.array(user_profiles_train), np.array(project_embeddings_train)],
    np.array(y_train),
    validation_data=([np.array(user_profiles_val), np.array(project_embeddings_val)], np.array(y_val)),
    epochs=30,  # You can adjust the number of epochs
    batch_size=4 # And the batch size
)

Epoch 1/30
5/5 [==============================] - 2s 70ms/step - loss: 0.2840 - accuracy: 0.4211 - val_loss: 0.2599 - val_accuracy: 0.3684
Epoch 2/30
5/5 [==============================] - 0s 17ms/step - loss: 0.2414 - accuracy: 0.5789 - val_loss: 0.2770 - val_accuracy: 0.3684
Epoch 3/30
5/5 [==============================] - 0s 13ms/step - loss: 0.2330 - accuracy: 0.5789 - val_loss: 0.2813 - val_accuracy: 0.4211
Epoch 4/30
5/5 [==============================] - 0s 18ms/step - loss: 0.2220 - accuracy: 0.6316 - val_loss: 0.2863 - val_accuracy: 0.4211
Epoch 5/30
5/5 [==============================] - 0s 14ms/step - loss: 0.2175 - accuracy: 0.6316 - val_loss: 0.2880 - val_accuracy: 0.4737
Epoch 6/30
5/5 [==============================] - 0s 13ms/step - loss: 0.2140 - accuracy: 0.6842 - val_loss: 0.2927 - val_accuracy: 0.4737
Epoch 7/30
5/5 [==============================] - 0s 13ms/step - loss: 0.1947 - accuracy: 0.7368 - val_loss: 0.2971 - val_accuracy: 0.4211
Epoch 8/30
5/5 [===========

In [ ]:
def create_user_vector(role: str, languages: list[str]):
  languages_vector = mlb.fit_transform([languages])

  pred_role_preprocessed = bert_preprocess_model([role])
  pred_role_results = bert_model(pred_role_preprocessed)
  pred_roles_embedded = pred_role_results['pooled_output']

  return tf.concat([pred_roles_embedded, languages_vector], axis=1)



In [ ]:
user_profile_example = create_user_vector("Machine learning, quantum computing phd student", ['Shell', 'Python', 'R', 'C++', 'Makefile'])
project_embedding_example = bert_model(bert_preprocess_model(['JQuery multiselect plugin based on Twitter Bootstrap.']))['pooled_output']

# Make a prediction
similarity_score = siamese_network.predict([user_profile_example, project_embedding_example])

# Output the similarity score
print("Similarity Score:", similarity_score[0][0])

1/1 [==============================] - 0s 81ms/step
Similarity Score: 1.1335626


Let's try ranking random projects for a given input user profile

In [ ]:
# rank projects testing
user_profile_example = create_user_vector("Senior Software Engineer @microsoft", ['Shell', 'PowerShell', 'C#', 'Python', 'JavaScript'])
num_projects = 19
rand_index = random.randint(num_projects+1, len(projects) - 1) - num_projects
rand_index = 0

print(rand_index)

predictions = []

for i in range(num_projects):
  project_embedding_example = bert_model(bert_preprocess_model([projects[rand_index + i]]))['pooled_output']
  similarity_score = siamese_network.predict([user_profile_example, project_embedding_example])
  predictions.append((projects[rand_index + i], similarity_score[0][0]))

0
1/1 [==============================] - 0s 40ms/step


In [ ]:
# Sort the predictions in descending order of the score
sorted_predictions = sorted(predictions, key=lambda x: x[1], reverse=True)

# Print the sorted predictions
for project, score in sorted_predictions:
  print(f"{project}: {score}")

Deep Learning based variant calling toolkit - https://clara-parabricks.github.io/VariantWorks/: 0.880397379398346
Community-curated list of software packages and data resources for single-cell, including RNA-seq, ATAC-seq, etc.: 0.8409087657928467
DL based processing of atac-seq data: 0.8351987600326538
Extracting mutational signatures via LASSO. The manuscript of the method is available as a preprint at: https://www.biorxiv.org/content/10.1101/384834v3: 0.831963062286377
Hackathon team: gene expression analysis for Covid-19: 0.8025743365287781
Examples of single-cell genomic analysis accelerated with RAPIDS: 0.7941628098487854
Training requirements for joining projects: 0.7786807417869568
Microsoft Azure Workshop for Developers: 0.5894323587417603
MkDocs Video plugin: 0.5631030201911926
OSC message decoder/encoder with fault tolerant: 0.4191855192184448
Single-Cell Analysis in Python. Scales to >1M cells.: 0.36352550983428955
A MkDocs plugin that lets you exclude/include docs files us

In [ ]:
for i in range(2):
  print(f"User {i}: {map_user_to_projects[i]}")

User 0: ['A collection of tasks to enable execution MySQL commands or scripts by VSTS/TFS Windows Agents.', 'Microsoft Azure Workshop for Developers', 'PowerShell module for interacting with Bluetooth Low Energy (BLE) devices implementing the Generic Attribute Profile (GATT/GAP)', 'Pre-commit hooks collection that utilizes ChatGPT and OpenAI platform to validate changes made to the codebase.', 'This GitHub Action allows you to run Gitleaks in your GitHub workflow.', 'A MkDocs plugin that lets you exclude/include docs files using globs, regexes, gitignore-style file and Markdown/FrontMatter tags metadata.', 'MkDocs Video plugin', 'OSC message decoder/encoder with fault tolerant', 'Detect non-inclusive language in your source code.']
User 1: ['DL based processing of atac-seq data', 'Community-curated list of software packages and data resources for single-cell, including RNA-seq, ATAC-seq, etc.', 'Hackathon team: gene expression analysis for Covid-19', 'Examples of single-cell genomic an

In [ ]:
num = 130
selected_rows = data.iloc[num:num+20]
print(selected_rows)

0                                                 role experience_level  \
374  a python/javascript/php/linux guru ready to ta...           Expert   
375                                Interested in Web3.           Expert   
377      ElectroMecahnical Engineer | Python | Arduino           Expert   
378                           Just this guy, you know?         Beginner   
386   I love GNOME and cats, like any self-respecti...           Expert   
398       Dragon boat paddler, Kitty Mama, rice lover.         Beginner   
400                                I build cool stuff!         Beginner   
401  Software is my medium for expressing ideas and...         Beginner   
402  UC Berkeley, California, USA.\ndaixili_cs@berk...     Intermediate   
404          Postdoc at the Coley Research Group, MIT.     Intermediate   
405  bioinformatician, computational biologist, com...     Intermediate   
406  Open-source software for volunteer computing a...     Intermediate   
410  I write, make games,